security:
  oauth2:
    client:
        clientId:
        clientSecret:
        accessTokenUri:
        userAuthorizationUri:
        clientAuthenticationScheme: form
      resource:
        userInfoUri:
        preferTokenInfo: